theme: jekyll-theme-minimal
title: [Dong-Ha Oh]
description: [Research assistant professor@LSU; plant comparative genomics; extremophyte genomics; invasive genomics; co-linearity; gene regulatory network (GRN); GRN modifications]
