theme: jekyll-theme-minimal
title: Dong-Ha Oh
logo: /assets/img/ohdongha_logo.jpg
description: plant abiotic stress response; comparative genomics; extremophyte genomics; invasive genomics; co-linearity / synteny; gene regulatory network (GRN); GRN evolution
