theme: jekyll-theme-minimal
title: [Dong-Ha Oh]
description: [Research assistant professor@LSU; plant abiotic stress response; comparative genomics; extremophyte genomics; invasive genomics; co-linearity / synteny; gene regulatory network (GRN); GRN evolution]
